version: '3'

volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    container_name: cowrie
    restart: always
    ports:
     - "22:2222"
     - "23:2223"
    image: "cowrie:latest"
    volumes:
     - cowrie-etc:/cowrie/cowrie-git/etc
     - cowrie-var:/cowrie/cowrie-git/var
